
# Presets allow Flexget to apply one set of actions to multiple
# tasks of the same type. Most importantly this means you don't
# type these things more than once.
presets:

  # This preset is for TV Shows.
  tvtorrent:
    # Use the exist_series plugin to recursively search through
    # the Series folder to check if the file to be downloaded
    # already exists.
    exists_series: /media/Series/
    # Don't use magnets because they get in the way of
    # the main_file_only plugin.
    magnets: no
    # Download the torrent using Deluge.
    deluge:
      # Self explanatory.
      user: deluge
      # Self explanatory.
      pass: deluge
      # Only download the biggest file. This means samples and
      #  jpgs don't get downloaded.
      main_file_only: yes
      # Makes the torrent conform to the global torrent settings
      # relating to seed times and seed ratios.
      automanaged: true
      # Rename the biggest file in the torrent to the following:
      # EG: Mad Men - S01E01
      # Flexget automatically understands this syntax.
      content_filename: '%(series_name)s - %(series_id)s'
      # When the main file is done, move it to the appropriate
      # folder.
      # EG: /media/Series/Mad Men/Season 1/
      movedone: /media/Series/%(series_name)s/Season %(series_season)d/
      # Finish seeding when the torrent reaches this ratio.
      ratio: 0.0001
      # Remove the torrent when it has reached this ratio.
      removeatratio: yes

  # This is for movies.
  movie:
    # Recursively search through MoviesHD to make sure that we
    # don't already have this movie in the library.
    exists_movie: /media/MoviesHD/
    # Use Deluge to download the torrent.
    deluge:
      # Self explanatory.
      user: deluge
      # Self explanatory.
      pass: deluge
      # Makes the torrent conform to the global torrent settings
      # relating to seed times and seed ratios.
      automanaged: true
      # Rename the folder according to the following criteria:
      # EG: The Interview (2014)
      # Note that due to the YTS task requiring IMDB info, Flexget
      # will automatically have all IMDB metadata on hand
      content_filename: "{{imdb_name}} ({{imdb_year}})"
      # Move the finished torrent folder to the MoviesHD folder.
      movedone: /media/MoviesHD/
      # Finish seeding when the torrent reaches this ratio.
      ratio: 0.0001
      # Remove the torrent when it has reached this ratio.
      removeatratio: yes

# These are the actual tasks to be completed, using the
# presets above.
tasks:

  # TV Show task, name is arbitrary.
  showRSS:
    # Use an RSS feed as the source. This it my custom showRSS
    # feed. Be sure that whatever Flexget is looking for is
    # actually in the RSS feed, otherwise it'll never
    # download anything.
    rss: http://showrss.info/rss.php?user_id=227669&hd=0&proper=1&
    magnets=false
    # Download the listed series.
    series:
      # Each series list listed, and Flexget will check the
      # RSS feed
      # for all entries.
      - Modern Family
      - Suits
      - Castle (2009)
      - Downton Abbey
      - Game of Thrones
      - Grey's Anatomy
      - How I Met Your Mother
      - Mad Men
      - The Blacklist
      - The Big Bang Theory
      - America's Next Top Model
      - Boardwalk Empire
      - Homeland
      - Elementary
      - Scandal (2012)
      - House of Cards (2013)
      - Glee
      - MythBusters
      - Sherlock
      - Top Gear
    # If an entry is found use the tvtorrent preset to
    # download it.
    preset:
      - tvtorrent

  # Task name for Movies, again arbitrary.
  YTS:
    # All 1080p movies from YIFI that have an IMDB score of at
    # least 7.
    rss: http://yts.re/rss/0/1080p/All/7
    # Download all entries, they have already been filtered.
    accept_all: yes
    # Override the accept_all and make sure that movies are not
    # downloaded if they have already been marked as downloaded by
    # Flexget
    seen_movies: strict
    # Make sure that Flexget can retrieve the full IMDB metadata
    # otherwise don't download the movie.
    imdb_required: yes
    # Apply the following IMDB filters to the list
    imdb:
      reject_genres:
        - horror
        - documentary
    # Only download 1 entry per execution of this task.
    limit_new: 1
    # Only download 1 entry per day.
    interval: 1 days
    # On accepted entries, download them using the movie preset.
    preset:
      - movie
