#name: Entropy Reduction
title: Entropy Reduction
description: Personal Log of Yet Another Digital Native.
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

theme: jekyll-theme-modernist
