name: dancingborg.github.io
title: Hacker Notes
description: An attempt at reducing entropy.
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

theme: jekyll-theme-hacker
