name: dancingborg.github.io
title: dancingborg.github.io
description: Yet another personal Github page.
markdown: redcarpet
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

theme: jekyll-theme-midnight
