name: Entropy Reduction
title: Entropy Reduction
description: Notes of another digital native.
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks

theme: jekyll-theme-midnight
