#name: Entropy Reduction
title: Entropy Reduction
description: Personal Log of Yet Another Digital Native.
redcarpet:
  extensions:
    - hard_wrap
    - no_intra_emphasis
    - autolink
    - strikethrough
    - fenced_code_blocks
# https://compile.blog/jekyll-blog-permalink-images/
permalink: /:title/
theme: jekyll-theme-minimal
# https://github.com/pages-themes/cayman/issues/29#issuecomment-339016299
github:
  is_project_page: false
